### numpy 모듈 호출

In [8]:
import numpy as np

In [12]:
a = np.array(1)
a

array(1)

### 배열 생성

In [13]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [14]:
ndarr_2 = np.array([1,2.0,3])
print(ndarr_2)
# float형식으로 저장됨

[1. 2. 3.]


In [15]:
ndarr_3 = np.array([1,2.0,'3'])
print(ndarr_3)
# string형식으로 저장됨

['1' '2.0' '3']


### 배열의 정보 확인
#### > 자료형 확인 속성
#### ndarray.dtype

In [16]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [17]:
print(np.array(1+2j).dtype)
print(np.array(print).dtype)

complex128
object


### 자료형 지정
#### > dtype 속성을 사용하여 자료형 지정

In [18]:
# int
dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)

int8


In [19]:
# float
dtype2 = np.array([1,2,3], dtype=float)
print(dtype2.dtype)

float64


In [20]:
# string
dtype3 = np.array([1,2,3], dtype=str)
print(dtype3.dtype)

<U1


### 자료형 지정
#### > 주의해야할점

In [21]:
dtype4 = np.array([1,2.1,'3'], dtype=int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


In [22]:
dtype5 = np.array([1,'data',print], dtype=float)
print(dtype5.dtype)

ValueError: could not convert string to float: 'data'

### 배열의 정보 확인
#### > 배열 크기 확인
#### ndarray.shape

In [23]:
print(ndarr_1.shape)

(3,)


#### > 배열 차원 확인
#### ndarray.ndim

In [24]:
print(ndarr_1.ndim)

1


### N차원 배열
#### Scalar : 숫자
#### Vector : Scalar의 배열, 1차월 배열
#### Matrix : Vector의 배열, 2차원 배열
#### Tensor : Matrix의 배열, 3차원 배열

### 배열 생성
#### 1차원 배열 생성

In [25]:
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


#### 2차원 배열 생성

In [26]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


#### 3차원 배열 생성

In [27]:
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


### 배열의 정보 확인
#### > 배열 요소의 개수 확인
#### ndarray.size

In [28]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


In [32]:
m1 = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(m1)
print(m1.shape) # 크기
print(m1.ndim) # 차원
print(m1.dtype) # 타입

[[1 2 3]
 [2 4 6]
 [3 6 9]]
(3, 3)
2
int32


### 자료형 변환(리스트)
#### > 리스트 -> ndarray 변환

In [33]:
list1 = [1,2,3]
arr1 = np.array(list1)
print(arr1)

[1 2 3]


#### > ndarray -> 리스트 변환

In [34]:
arr2 = np.array([1,2,3])
list2 = list(arr2)
print(list2)

[1, 2, 3]


### 자료형 변환(리스트)
#### > 2차원 리스트 변환

In [35]:
list3 = [[1,2,3],[4,5,6]]
arr3 = np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


#### 주의해야 할 점 - list의 shape 다른 경우

In [38]:
list4 = [[1,2,3,4],[5,6,7]]
arr4 = np.array(list4)
print(arr4)### 자료형 변환(리스트)
#### > 2차원 리스트 변환

[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\admin\AppData\Local\Temp\ipykernel_11644\2158651982.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


### 자료형 변환(튜플) - 리스트와 동일
#### > 튜플 -> ndarray 변환

In [39]:
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

[1 2 3]


#### > ndarray -> 튜플 변환

In [40]:
arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(tuple2### 자료형 변환(튜플) - 리스트와 동일
#### > 튜플 -> ndarray 변환)

(1, 2, 3)


### 자료형 변환(세트, 딕셔너리)
#### > 세트 변환

In [41]:
set1 = {1,2,3}
arr = np.array(set1)
print(arr)

{1, 2, 3}


In [42]:
print(arr.size)

1


### 자료형 변환(세트, 딕셔너리)
#### > 딕셔너리 변환

In [43]:
dict1 = {'a':1,'b':2,'c':3}
arr = np.array(dict1)
print(arr)

{'a': 1, 'b': 2, 'c': 3}


In [44]:
print(arr.size)

1


### 배열 인덱싱
#### > 리스트 인덱싱과 유사
#### - ndarray[col]
#### - ndarray[row][col]
#### - ndarray[rank][row][col]

In [46]:
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]
# 1 가져오기
print(list_[0][0][0])
# 4 가져오기
print(list_[0][1][1])
# 7 가져오기
print(list_[1][1][0])

1
4
7


### 배열 인덱싱
#### > 리스트 인덱싱과 유사
#### - array[col]
#### - array[row][col]
#### - array[rank][row][col]

In [48]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# 1 가져오기
print(arr_[0,0,0])
# 4 가져오기
print(arr_[0,1,1])
# 7 가져오기
print(arr_[1,1,0])

1
4
7


In [49]:
arr_1 = np.array([[1,2],
                 [3,4],
                 [5,6]])
# 0행 가져와 2차원 배열 만들기
print(arr_1[[0]])
# 0,2행 가져와 2차원 배열 만들기
print(arr_1[[0,2]])
# 0,2행 가져와 2차원 배열 만들기
print(arr_1[[0,1,2],    # row1,co1 = 0.0 
            [0,1,0]])   # row2,col2 = 1.1 / row3,col3 = 2,0
# 같은 위치 데이터 여러번 사용가능
print(arr_1[[0,0],[1,1]])

[[1 2]]
[[1 2]
 [5 6]]
[1 4 5]
[2 2]


In [51]:
arr_2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])
# 두 개의 1차원 배열 만들기
b = np.array([0,1,2,3])
c = np.array([0,2,0,1])
# 다음 코드의 실행 결과는?
print(arr_2[b,c])

[ 1  6  7 11]


### 배열 인덱싱
#### > Boolean 인덱싱


In [52]:
# 기본 데이터
arr = np.array([1,2,3,4,5])

In [55]:
# True, False
print(arr[[True,False,True,True,False]])

[1 3 4]


In [56]:
# 조건
print(arr[arr>=3])

[3 4 5]


### 배열 인덱싱
#### [문제2]


In [59]:
score = np.array([[78,91,84,89,93,65],
                  [82,87,96,79,91,73]])
print(score[0][score[0] >= 90])
print(score[1][score[1] >= 90])

[91 93]
[96 91]
