In [5]:
import numpy as np

### 파일 처리
#### ndarray의 정보를 파일로 저장할 수 있다
#### 일반적인 파일 확장자는 npy를 사용한다
#### > 파일저장(tofile)

In [16]:
n = np.random.randn(3,5)
print(n)
n.tofile('n.txt')

[[-0.09260287 -2.44653968 -0.53214874  1.22801376 -0.6792629 ]
 [-0.55379885  0.44892923 -0.184086    0.02294976  1.51867838]
 [-0.8890115  -0.9099365   1.31653445 -0.78497859 -0.37641214]]


### 파일 처리
#### > 파일 불러오기(fromfile)

In [17]:
m = np.fromfile('n.npy')
m1 = np.fromfile('C:/STUDY/Python/n.npy') # 절대경로 지정
print(m) # shape 무너짐

[-0.56349543  0.5324758   0.38034709  0.08443707  0.19433338  0.65935538
 -0.44187372  1.165042    1.49462546  1.4348234  -0.98508045  1.27518907
  1.19967667 -0.40788306 -0.47911074]


### 파일 처리
#### > 파일 불러오기(np.save, np.load)

In [19]:
np.save('n.npy',n)
m1 = np.load('n.npy')
print(m1)

[[-0.09260287 -2.44653968 -0.53214874  1.22801376 -0.6792629 ]
 [-0.55379885  0.44892923 -0.184086    0.02294976  1.51867838]
 [-0.8890115  -0.9099365   1.31653445 -0.78497859 -0.37641214]]


In [5]:
# n.tofile > n.npy 이렇게 저장한걸
# np.load('n.npy') 이렇게 불러오진 못함 (배열이 안맞음)

### 파일 처리
#### > 파일 불러오기(np.save, np.load)

In [23]:
np.savetxt('n.csv',n)

n.csv


In [24]:
np.loadtxt('n.csv')

array([[-0.09260287, -2.44653968, -0.53214874,  1.22801376, -0.6792629 ],
       [-0.55379885,  0.44892923, -0.184086  ,  0.02294976,  1.51867838],
       [-0.8890115 , -0.9099365 ,  1.31653445, -0.78497859, -0.37641214]])

### 파일처리
#### 문제

In [30]:
# 1~25 범위의 5x5 2차원 행렬을 생성하고 구분자(delimiter)는 ,(콤마)로 지정해서 data.csv에 지정해봅시다
matrix = np.arange(1,26).reshape(5,5)
matrix = np.savetxt('data.csv',n,delimiter = ',')

arr = np.arange(1,26, dtype = np.int8).reshape(5,5)
np.savetxt('data.csv',arr,delimiter=',')

In [35]:
# 06_data1.txt. 파일을 읽어와서 dtype = str으로 변수 arr1에 저장하고 출력해 봅시다
arr1 = np.loadtxt('06_data1.txt', dtype = str)
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [45]:
# 06_data2.txt 파일을 읽어와서 변수 arr2에 저장핳고 출력해봅시다
arr2 = np.loadtxt('06_data2.txt',delimiter = ',')
print(arr2)

[[ 1. 15. 14.  4.]
 [12.  6.  7.  9.]
 [ 8. 10. 11.  5.]
 [13.  3.  2. 16.]]


### 문제2

In [60]:
# 파일 읽어와서 상위 5개 데이터 출력
data = np.loadtxt('./data/ex1_지역별전기요금.csv', delimiter = ',', dtype = int)
print(data[:5,:])

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [61]:
# 데이터 모양 확인
print(data.shape)
# 중복 지역 확인
print(np.unique(data[:,0]))

(17, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [63]:
# 데이터의 크기순 정렬 (argsort 사용)
print(data[:,1].argsort())
# fancy index
print(data[data[:,1].argsort()])
# 반대로 print(data[data[:,1].argsort()[::-1]])

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]
[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]


In [64]:
# 전국 대상 가구수의 합
print(np.sum(data[:,1]))
# 가구당 평균 전력 사용량의 전국 평균값
print(round(data[:,2].mean(),2))

14882047
335.18


In [114]:
# 무식하게 평균 구하기
a = np.sum(data[:,2])
print(a)
print(data.shape)
print('가구당 평균 전력 사용량의 전국 평균값 =',a / 17)

5698
(17, 4)
가구당 평균 전력 사용량의 전국 평균값 = 335.1764705882353


In [71]:
# 가구당 평균 전력 사용량이 평균 이상인 지역과 대상 가구수 추출
avg_ = data[:,2].mean()   # 가구당 평균 전력 사용량의 전국 평균
print(data[data[:,2] > avg_,0:2])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


### 문제2
#### ex2_전년대비_시도별_교통사망사고 데이터

In [93]:
# 1 위 파일을 읽어오고 상위 3개의 (발생년도, 발생건수, 구성비) 의  데이터 추출
ex2 = np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv',
                 delimiter = ',',
                 dtype = int)
print(ex2[:3,:])


[[2014    1  218    4   -9   -4]
 [2014    2  872   19  -45   -4]
 [2014    3  401    8  -45  -10]]


In [94]:
# 2 위 데이터에서 부산에서 발생한 교통사망사고 모든 현황을 추출
print(ex2[7,:])

[2014    8  163    3  -47  -22]


In [96]:
# 3 위 데이터에서 전국 사고 발생건수의 합계와 전국 평균을 계산
print(np.sum(data[:,2]))
print(np.mean(data[:,2]))

5698
335.1764705882353


In [102]:
# 4 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출
a = ex2[ex2[:,4].argsort()[::-1]]
print(a[0,:])

[2014    6  182    4   19   11]


In [106]:
# 5 교통사고 증감률이 가장 낮은 지역의 모든 현황을 추출
b = ex2[ex2[:,5].argsort()]
print(b[0,:])

[2014    8  163    3  -47  -22]


In [143]:
# 위 데이터에서 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증가수, 증감률 추출
c = ex2[np.where(ex2[:,2]>=400)]
c = c[:,[1,2,4,5]]
print(c)

[[  2 872 -45  -4]
 [  3 401 -45 -10]
 [  4 464 -41  -8]
 [ 13 400 -35  -8]]
