### Numpy 활용
#### Reshape
#### - 배열의 shape을 변형해주는 함수
#### - 배열의 요소 개수를 유지하며 형태만 변경
#### - 변형 전 size와 변형 후 size가 동일해야 함
#### > array.reshape(size)

In [2]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
# 3 x 1 x 2 배열로 변형
print(arr.reshape(3,1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [6]:
# 
print(arr.reshape(6))

[1 2 3 4 5 6]


In [ ]:
# [문제 1]
range() 함수를 사용해 1부터 36까지의 숫자가 나열된 tensor배열을 생성하고 (3,3,4)

#### 배열을 2차원 배열로 변형시켜봅니다. 열의 개수는 9

In [9]:
tensor = np.array(range(1,37))
tensor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [12]:
print(tensor.reshape(9,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]


### Flatten
#### 다차원 배열은 1차원 배열로 만들기
#### > flatten()

In [13]:
print(arr.flatten())

[1 2 3 4 5 6]


In [17]:
print(tensor.reshape(3,3,4).flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


### Arange
#### range 함수와 비슷한 기능
#### 값의 범위를 지정하여 값이 채워져 있는 배열을 생성
#### 특정한 규칙에 따라 증가하는 값을 넣는 것도 가능
#### > np.arange(size)

In [18]:
print(np.arange(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


### Arange
#### 간격 지정 : np.arange()
#### > np.arange(start, end, step)

In [19]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [21]:
print(np.arange(10, 0, -2))

[10  8  6  4  2]


### Arange + Reshape
#### 배열 요소를 순서대로 가지는 다차원 배열 생성 가능
#### > arange().reshape()

In [22]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
np.arange(0,6,0.2).reshape(3,2,5)

array([[[0. , 0.2, 0.4, 0.6, 0.8],
        [1. , 1.2, 1.4, 1.6, 1.8]],

       [[2. , 2.2, 2.4, 2.6, 2.8],
        [3. , 3.2, 3.4, 3.6, 3.8]],

       [[4. , 4.2, 4.4, 4.6, 4.8],
        [5. , 5.2, 5.4, 5.6, 5.8]]])

In [39]:
# [문제3] 100부터 190까지의 숫자가 10간격으로 배열 생성, (2,5)형태의 2차원 배열로 변형
print(np.arange(100,191,10).reshape(2,5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


In [38]:
# [문제4] -2부터 2까지의 숫자가 0.5로 나열된 배열 생성, 3차원 배열로 변형
print(np.arange(-2, 2.1, 0.5).reshape(3,1,3))

[[[-2.  -1.5 -1. ]]

 [[-0.5  0.   0.5]]

 [[ 1.   1.5  2. ]]]


### Zeros
#### 0으로 채워진 배열 생성
#### shape 지정이 가능
#### > np.zeros(shape, dtype)

In [40]:
print(np.zeros(shape=(5,), dtype=np.int8))

[0 0 0 0 0]


In [41]:
np.zeros((5),int)

array([0, 0, 0, 0, 0])

In [42]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


### Ones
#### 1으로 채워진 배열 생성
#### shape 지정이 가능
#### > np.ones(shape, dtype)

In [43]:
print(np.ones(shape=(5,), dtype=np.int8))

[1 1 1 1 1]


In [44]:
np.ones((5),int)

array([1, 1, 1, 1, 1])

In [45]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


### Empty
#### shape만 주어지고 비어있는 배열 생성
#### 배열을 생성만 하고 값을 주지 않아 메모리에 저장되어 있던 기존값이 저장될 수 있음
#### > np.empty(shape, dtype)

In [47]:
print(np.empty(shape = (10,), dtype = np.int32))

[100 110 120 130 140 150 160 170 180 190]


In [48]:
print(np.empty((2,5),np.int8))

[[ 96  96  72 -31   1]
 [  1   0   0   0   0]]
