### Full
#### 입력 값으로 채워지는 행렬
#### > np.full((shape), value)

In [2]:
import numpy as np

In [3]:
print(np.full((2,5), 3))

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [4]:
print(np.full((5,4),'a'))

[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


### Random.randint
#### 주어진 범위 안의 랜덤한 값을 뽑는 함수
#### > np.random.randint(range)

In [5]:
# 0~5까지의 정수 중 하나 뽑기
print(np.random.randint(6))

4


In [7]:
# 1~19까지의 정수 중 하나 뽑기
print(np.random.randint(1,20))

3


### Random.randn
#### 랜덤한 값으로 채워지는 배열
#### 평균 0, 표준편차 1의 가우시안 표준정규분포 난수를 shape 형태의 배열로 생성
#### > np.random.randn(shape)

In [8]:
print(np.random.randn(3))

[2.09505173 3.19515661 0.36314263]


In [9]:
print(np.random.randn(3,2))

[[ 0.6556611  -0.91621633]
 [-0.52565832 -0.74775063]
 [-1.76327033 -1.02068322]]


### 합 (sum)
#### 요소들의 합을 구해주는 함수
#### 2차원 배열 합 > ndarray.sum()

In [11]:
matrix = np.arange(1,7).reshape(2,3)

In [12]:
matrix.sum()

21

In [14]:
print(matrix.sum(axis=0))

[5 7 9]


### 합 (sum)
#### 3차원 배열 합

In [15]:
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171


In [19]:
print(tensor.sum(axis=0))
print(tensor.sum(axis=1))
print(tensor.sum(axis=2))

[[21 24 27]
 [30 33 36]]
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
[[ 6 15]
 [24 33]
 [42 51]]


In [21]:
print(tensor.sum(axis=0))
print(np.sum(tensor, axis=0)) # 출력은 같으나 표현이 다름

[[21 24 27]
 [30 33 36]]
[[21 24 27]
 [30 33 36]]


### 평균 (mean)
#### 합과 동일
#### > 2차원 배열 평균

In [18]:
print(matrix.mean())       # 전체 평균
print(matrix.mean(axis=0)) # 행끼리 평균(위 아래)
print(matrix.mean(axis=1)) # 열끼리 평균(좌 우)

3.5
[2.5 3.5 4.5]
[2. 5.]


### 표준 편차 (std)
#### 합, 평균과 동일
#### > 2차원 배열 표준 편차

In [22]:
print(matrix.std())       # 전체 표준 편차
print(matrix.std(axis=1)) # 행끼리 표준 편차(위 아래)
print(matrix.std(axis=2)) # 열끼리 표준 편차(좌 우)

1.707825127659933
[0.81649658 0.81649658]


AxisError: axis 2 is out of bounds for array of dimension 2

### 그 외 수학 연산자
#### 지수 > exp
#### 로그 > log
#### 제곱근 > sqrt
#### 삼각함수 > sin
#### 삼각함수 > cos
#### 삼각함수 > tan

In [26]:
print(np.exp(matrix))
print(np.log(matrix))
print(np.sqrt(matrix))
print(np.sin(matrix))
print(np.cos(matrix))
print(np.tan(matrix))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


### 배열 정렬 (Sort)
#### 1차원 배열 정렬

In [27]:
# 1~100 숫자 중 5개를 뽑아 배열 생성
vector = np.array([np.random.randint(1,100) for n in range(5)])
print(vector)

[16 28 77 30 10]


In [29]:
print(np.sort(vector))       # 오름차순 정렬
print(np.sort(vector)[::-1]) # 내림차순 정렬

[10 16 28 30 77]
[77 30 28 16 10]


In [30]:
# 리스트 내 for문
list_ = [1,2,3,4,5,6,7,8,9,10]
list_1 = [num * 3 for num in list_ if num % 2 == 1]
list_1

[3, 9, 15, 21, 27]

### 배열 정렬 (Sort)
#### 2차원 배열 정렬

In [32]:
# randint를 사용하여 1~100 숫자 중 20개를 뽑아 배열 생성
matrix = np.array([np.random.randint(1,101)
                  for n in range(20)]).reshape(4,5)
print(matrix)

[[  7   5  27  28  41]
 [ 66  79  92  71   4]
 [ 17  69  95  53  63]
 [ 10  94 100  51  16]]


In [33]:
print(np.sort(matrix)) # 열 기준으로 정렬

[[  5   7  27  28  41]
 [  4  66  71  79  92]
 [ 17  53  63  69  95]
 [ 10  16  51  94 100]]


In [34]:
print(np.sort(matrix, axis = 0)) # 행 기준으로 정렬

[[  7   5  27  28   4]
 [ 10  69  92  51  16]
 [ 17  79  95  53  41]
 [ 66  94 100  71  63]]


### 배열 합치기 (Vstack)
#### 2개 이상의 배열을 수직으로 합체
#### > np.vstack(arr1, arr2)
#### 2개 이상의 배열을 수평으로 합체
#### > np.hstack(arr1, arr2)

In [36]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

np.vstack([vector1,vector2])

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

np.hstack([vector1,vector2])

array([[1, 4],
       [2, 5],
       [3, 6]])

### 배열 합치기 (Concatenate)
#### 2개 이상의 배열을 수평, 수직으로 합체
#### > np.concatenate(arr1, arr2, axis)

In [46]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
np.concatenate([vector1, vector2])

array([1, 2, 3, 4, 5, 6])

In [45]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)
np.concatenate([vector1, vector2], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1, matrix2],axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 행 / 열 바꾸기 (transpose)
#### 행과 열을 뒤집어 주는 함수
#### > ndarray.transpose()
#### > ndarray.T

In [51]:
matrix3 = np.array([[5,6]])
print(matrix3)


[[5 6]]


In [59]:
print(matrix3.transpose())

[[5]
 [6]]


### Transpose + Concatenate
#### > 형태를 바꿔 서로 결합할 수 없는 배열을 합칠 수 있다

In [66]:
print(np.concatenate([matrix1,matrix3]))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(np.concatenate([matrix1,matrix3]))

### 인덱스 반환 함수
#### > 최대값, 최소값의 인덱스
#### argmax, argmin

In [69]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [70]:
print(np.argmax(a), np.argmin(a))

9 0


In [71]:
print(np.argmax(a, axis=0)) # 수직 비교

[1 1 1 1 1]


In [72]:
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]


In [75]:
print(np.argmax(b, axis=1)) # 가로 비교

[3 2 1]


In [74]:
print(np.argmax(b, axis=0)) # 세로 비교

[2 2 1 0]


### 배열 인덱싱(Fancy Index)
#### > 인덱스의 값을 가지는 배열을 통해 인덱싱

In [76]:
a = np.arange(1,11)
b = np.array([3,4,5,6])
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]


In [77]:
print(a[b])

[4 5 6 7]


### 배열 인덱싱
#### > 인덱스 반환 함수 + fancy index

In [78]:
a = np.arange(10,20)
b = np.argmax(a)
print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]
9


In [79]:
print(a[b])

19
