In [1]:
import numpy as np

### 파일 처리
#### ndarray의 정보를 파일로 저장할 수 있다
#### 일반적인 파일 확장자는 npy를 사용한다
#### > 파일저장(tofile)

In [2]:
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[-0.56349543  0.5324758   0.38034709  0.08443707  0.19433338]
 [ 0.65935538 -0.44187372  1.165042    1.49462546  1.4348234 ]
 [-0.98508045  1.27518907  1.19967667 -0.40788306 -0.47911074]]


### 파일 처리
#### > 파일 불러오기(fromfile)

In [3]:
m = np.fromfile('n.npy')
m1 = np.fromfile('C:/STUDY/Python/n.npy') # 절대경로 지정
print(m) # shape 무너짐

[-0.56349543  0.5324758   0.38034709  0.08443707  0.19433338  0.65935538
 -0.44187372  1.165042    1.49462546  1.4348234  -0.98508045  1.27518907
  1.19967667 -0.40788306 -0.47911074]


### 파일 처리
#### > 파일 불러오기(np.save, np.load)

In [4]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[-0.56349543  0.5324758   0.38034709  0.08443707  0.19433338]
 [ 0.65935538 -0.44187372  1.165042    1.49462546  1.4348234 ]
 [-0.98508045  1.27518907  1.19967667 -0.40788306 -0.47911074]]


In [5]:
# n.tofile > n.npy 이렇게 저장한걸
# np.load('n.npy') 이렇게 불러오진 못함 (배열이 안맞음)