### 배열 슬라이싱
#### > ndarray의 슬라이싱

In [9]:
import numpy as np

In [24]:
matrix = np.array([[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
# 0열 전체 슬라이싱
print(matrix[:,0])

[ 1  6 11 16]


In [26]:
# 0열 전체 슬라이싱(2차원 유지)
print(matrix[:,:1])

[[ 1]
 [ 6]
 [11]
 [16]]


In [27]:
# 1행 전체 슬라이싱
print(matrix[1,:])

[ 6  7  8  9 10]


In [28]:
# 1행 전체 슬라이싱
print(matrix[1]) # rank > row > col 순으로 :(콜론) 생략가능

[ 6  7  8  9 10]


In [29]:
# 1행 전체 슬라이싱 (2차원 유지)
print(matrix[1:2,:]) # or print(matrix[[1]])

[[ 6  7  8  9 10]]


In [30]:
# 3~4열 전체 슬라이싱
print(matrix[:,3:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [32]:
# 0행, 1~3열 슬라이싱
print(matrix[0,1:-1])

[2 3 4]


In [34]:
# 2~3행, 2~4열 슬라이싱
print(matrix[-2:,-3:])

[[13 14 15]
 [18 19 20]]


In [35]:
# 1~2행, 1~2열 슬라이싱
print(matrix[1:-1,1:3])

[[ 7  8]
 [12 13]]


### 배열 인덱싱, 슬라이싱 복합
#### > ndarray의 슬라이싱

In [36]:
# 1,3행, 2~4열 슬라이싱
print(matrix[[1,3],2:])

[[ 8  9 10]
 [18 19 20]]


In [37]:
# 1~2행, 1,3열 슬라이싱
print(matrix[1:-1,[1,3]])

[[ 7  9]
 [12 14]]


In [51]:
# [문제3]
# [10 2 6] 뽑아내기
tensor = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])
print(tensor)
print(tensor[[1,0,0],[1,0,1],[0,1,2]])
# [rank][row][col]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[10  2  6]


In [57]:
# [문제4]
# 문제3의 tensor 배열에서 인덱싱, 슬라이싱을 사용해 [[1 2][4 5]] 배열과 [9 12] 배열을 추출해봅시다
print(tensor[0,:,0:2])
print(tensor[1,:,-1])

[[1 2]
 [4 5]]
[ 9 12]
