### 산술연산
#### 배열은 기본적으로 요소의 연산이 가능

In [3]:
import numpy as np

In [1]:
# 리스트의 덧셈
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [4]:
# 배열의 덧셈
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]


### 산술연산
#### shape이 같은 배열은 연산 가능

In [16]:
arr1 = np.arange(1,7).reshape(2,3)
arr1 = np.arange(11,17).reshape(2,3)
print(arr1+arr2) # 더하기

[[15 17 19]
 [18 20 22]]


In [17]:
print(arr2 - arr1)  # 뺄셈
print(arr1 * arr2)  # 곱셈
print(arr1 / arr2)  # 나누기
print(arr1 ** arr2) # 제곱
print(arr1 // arr2) # 몫
print(arr2 % arr1)  # 나머지

[[ -7  -7  -7]
 [-10 -10 -10]]
[[44 60 78]
 [56 75 96]]
[[2.75       2.4        2.16666667]
 [3.5        3.         2.66666667]]
[[   14641   248832  4826809]
 [   38416   759375 16777216]]
[[2 2 2]
 [3 3 2]]
[[4 5 6]
 [4 5 6]]


In [18]:
arr1.dtype

dtype('int32')

### 산술연산
#### Numpy의 연산 함수
#### np.add(arr1, arr2)
#### np.subtract(arr1, arr2)
#### np.multiply(arr1, arr2)
#### np.divide(arr1, arr2)

In [21]:
print(arr1 +arr2)
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[[15 17 19]
 [18 20 22]]
[[15 17 19]
 [18 20 22]]
[[ 7  7  7]
 [10 10 10]]
[[44 60 78]
 [56 75 96]]
[[2.75       2.4        2.16666667]
 [3.5        3.         2.66666667]]


### 산술연산
#### Broadcasting
#### 연산하고자 하는 배열의 모양이 다른 경우의 연산

In [23]:
arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(10).reshape(2,5)
# print(arr3 + arr4) 에러

In [26]:
# 배열과 스칼라의 연산
scalar = 10
vector = np.array([1,2,3])
print(scalar + vector)
print(scalar - vector)
print(scalar * vector)
print(scalar / vector)

[11 12 13]
[9 8 7]
[10 20 30]
[10.          5.          3.33333333]


In [27]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar + matrix)
print(scalar - matrix)
print(scalar * matrix)
print(scalar / matrix)

[[11 12 13]
 [14 15 16]]
[[9 8 7]
 [6 5 4]]
[[10 20 30]
 [40 50 60]]
[[10.          5.          3.33333333]
 [ 2.5         2.          1.66666667]]


In [29]:
scalar = 10
tensor = np.array([[[1,2,3,],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [13,14,15],[16,17,18]])
print(scalar + tensor)

C:\Users\admin\AppData\Local\Temp\ipykernel_13356\109059102.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tensor = np.array([[[1,2,3,],[4,5,6]],


TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [30]:
# 벡터와 매트릭스의 연산
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix+vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [31]:
# 벡터와 벡터의 브로드캐스팅 연산
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)
print(arr1 + arr2)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 행렬연산
#### np.dot(arr1, arr2) 함수사용

In [32]:
# 일반적인 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1 * arr2)

[1 4 9]


In [34]:
# np.dot 사용 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(np.dot(arr1,arr2))
print(arr1.dot(arr2))
print(arr1 @ arr2)

14
14
14


In [36]:
# 2차원 배열 행렬곱
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(np.dot(arr3,arr4))

[[ 82  88]
 [199 214]]
