In [1]:
import numpy as np

In [2]:
# 1. NAND w1, w2, theta
# 2. AND w1, w2, theta
# 3. OR w1, w2, theta
# 함수 and 논리를 출력하는 함수
# 함수 nand 논리를 출력하는 함수
# 함수 or 논리를 출력하는 함수
# 함수 xor 논리를 출력하는 함수

In [9]:
X = np.array([[0,1,0,1],[0,0,1,1]]).T

In [62]:
def AND(X):
    W = np.array([[0.1],[0.1]])
    theta = 0.1111111111111
    return np.where(np.dot(X,W) > theta, 1, 0)

def OR(X):
    W = np.array([[0.1],[0.1]])
    theta = 0
    return np.where(np.dot(X,W) > theta, 1, 0)

def NAND(X):
    W = np.array([[0.1],[0.1]])
    theta = 0.11
    return np.where(np.dot(X,W) < theta, 1, 0)

def XOR(X):
    x = np.c_[NAND(X), OR(X)]
    return AND(x)

In [67]:
# XOR(X)
def XOR(X):
    W1 = np.array([[0.1,0.1],[0.1,0.2]])
    W2 = np.array([[0.1],[0.1]])
    b1 = 0.1
    b2 = 0.1
    layer1 = np.where(np.dot(X, W1) > b1 ,1,0)
    layer2 = np.where(np.dot(layer1,W2) > b2, 1,0)
    return layer2

In [68]:
print(AND(X))
print(OR(X))
print(NAND(X))
print(XOR(X))

[[0]
 [0]
 [0]
 [1]]
[[0]
 [1]
 [1]
 [1]]
[[1]
 [1]
 [1]
 [0]]
[[0]
 [0]
 [0]
 [1]]


In [48]:
w1s = np.linspace(0.1,1,10)
w2s = np.linspace(0.1,1,10)
thetas = np.linspace(0.1,1,10)

# AND
for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1 + X[:,1]*w2 > theta, 1, 0)
            if np.sum(result == np.array([0,0,0,1])) == 4:
                print(w1,w2,theta)

0.1 0.1 0.1
0.1 0.2 0.2
0.1 0.30000000000000004 0.30000000000000004
0.1 0.4 0.4
0.1 0.5 0.5
0.1 0.6 0.6
0.1 0.7000000000000001 0.7000000000000001
0.1 0.8 0.8
0.1 0.9 0.9
0.1 1.0 1.0
0.2 0.1 0.2
0.2 0.2 0.2
0.2 0.2 0.30000000000000004
0.2 0.30000000000000004 0.30000000000000004
0.2 0.30000000000000004 0.4
0.2 0.4 0.4
0.2 0.4 0.5
0.2 0.4 0.6
0.2 0.5 0.5
0.2 0.5 0.6
0.2 0.6 0.6
0.2 0.6 0.7000000000000001
0.2 0.7000000000000001 0.7000000000000001
0.2 0.7000000000000001 0.8
0.2 0.7000000000000001 0.9
0.2 0.8 0.8
0.2 0.8 0.9
0.2 0.9 0.9
0.2 0.9 1.0
0.2 1.0 1.0
0.30000000000000004 0.1 0.30000000000000004
0.30000000000000004 0.2 0.30000000000000004
0.30000000000000004 0.2 0.4
0.30000000000000004 0.30000000000000004 0.30000000000000004
0.30000000000000004 0.30000000000000004 0.4
0.30000000000000004 0.30000000000000004 0.5
0.30000000000000004 0.30000000000000004 0.6
0.30000000000000004 0.4 0.4
0.30000000000000004 0.4 0.5
0.30000000000000004 0.4 0.6
0.30000000000000004 0.5 0.5
0.30000000000000004

In [49]:
result == np.array([0,0,0,1])

array([ True,  True,  True,  True])

In [25]:
# OR
for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1 + X[:,1]*w2 >= theta, 1, 0)
            if np.sum(result == np.array([0,1,1,1])) == 4:
                print(w1,w2,theta)

0.1 0.1 0.1
0.1 0.2 0.1
0.1 0.30000000000000004 0.1
0.1 0.4 0.1
0.1 0.5 0.1
0.1 0.6 0.1
0.1 0.7000000000000001 0.1
0.1 0.8 0.1
0.1 0.9 0.1
0.1 1.0 0.1
0.2 0.1 0.1
0.2 0.2 0.1
0.2 0.2 0.2
0.2 0.30000000000000004 0.1
0.2 0.30000000000000004 0.2
0.2 0.4 0.1
0.2 0.4 0.2
0.2 0.5 0.1
0.2 0.5 0.2
0.2 0.6 0.1
0.2 0.6 0.2
0.2 0.7000000000000001 0.1
0.2 0.7000000000000001 0.2
0.2 0.8 0.1
0.2 0.8 0.2
0.2 0.9 0.1
0.2 0.9 0.2
0.2 1.0 0.1
0.2 1.0 0.2
0.30000000000000004 0.1 0.1
0.30000000000000004 0.2 0.1
0.30000000000000004 0.2 0.2
0.30000000000000004 0.30000000000000004 0.1
0.30000000000000004 0.30000000000000004 0.2
0.30000000000000004 0.30000000000000004 0.30000000000000004
0.30000000000000004 0.4 0.1
0.30000000000000004 0.4 0.2
0.30000000000000004 0.4 0.30000000000000004
0.30000000000000004 0.5 0.1
0.30000000000000004 0.5 0.2
0.30000000000000004 0.5 0.30000000000000004
0.30000000000000004 0.6 0.1
0.30000000000000004 0.6 0.2
0.30000000000000004 0.6 0.30000000000000004
0.30000000000000004 0.70000

In [26]:
result

array([0, 1, 1, 1])

In [30]:
# NAND
for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1 + X[:,1]*w2 <= theta, 1, 0)
            if np.sum(result == np.array([1,1,1,0])) == 4:
                print(w1,w2,theta)

0.1 0.1 0.1
0.1 0.2 0.2
0.1 0.30000000000000004 0.30000000000000004
0.1 0.4 0.4
0.1 0.5 0.5
0.1 0.6 0.6
0.1 0.7000000000000001 0.7000000000000001
0.1 0.8 0.8
0.1 0.9 0.9
0.1 1.0 1.0
0.2 0.1 0.2
0.2 0.2 0.2
0.2 0.2 0.30000000000000004
0.2 0.30000000000000004 0.30000000000000004
0.2 0.30000000000000004 0.4
0.2 0.4 0.4
0.2 0.4 0.5
0.2 0.4 0.6
0.2 0.5 0.5
0.2 0.5 0.6
0.2 0.6 0.6
0.2 0.6 0.7000000000000001
0.2 0.7000000000000001 0.7000000000000001
0.2 0.7000000000000001 0.8
0.2 0.7000000000000001 0.9
0.2 0.8 0.8
0.2 0.8 0.9
0.2 0.9 0.9
0.2 0.9 1.0
0.2 1.0 1.0
0.30000000000000004 0.1 0.30000000000000004
0.30000000000000004 0.2 0.30000000000000004
0.30000000000000004 0.2 0.4
0.30000000000000004 0.30000000000000004 0.30000000000000004
0.30000000000000004 0.30000000000000004 0.4
0.30000000000000004 0.30000000000000004 0.5
0.30000000000000004 0.30000000000000004 0.6
0.30000000000000004 0.4 0.4
0.30000000000000004 0.4 0.5
0.30000000000000004 0.4 0.6
0.30000000000000004 0.5 0.5
0.30000000000000004

In [31]:
result

array([1, 1, 1, 0])

In [34]:
# XOR
for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1 + X[:,1]*w2 == theta, 1, 0)
            if np.sum(result == np.array([0,1,1,0])) == 4:
                print(w1,w2,theta)

0.1 0.1 0.1
0.2 0.2 0.2
0.30000000000000004 0.30000000000000004 0.30000000000000004
0.4 0.4 0.4
0.5 0.5 0.5
0.6 0.6 0.6
0.7000000000000001 0.7000000000000001 0.7000000000000001
0.8 0.8 0.8
0.9 0.9 0.9
1.0 1.0 1.0


In [33]:
result

array([0, 1, 1, 0])